name: WIP Action
description: Mark a pull request commits with pending state if it finds specified terms in the pull request title or label.
author: bubkoo <bubkoo.wy@gmail.com>

inputs:
  GITHUB_TOKEN:
    required: true
    description: Your GitHub token for authentication.

  setFailed:
    required: false
    description: Set action to failed when wip.

  config:
    required: false
    description: Match with PR labels. Comma separated and case insensitive labels.

  check_name:
    required: false
    description: |
      A string label to differentiate this status from the status of other systems.
      This field is case-insensitive.
    default: WIP

  target_url:
    required: false
    description: |
      The target URL to associate with this status. This URL will be linked from the GitHub UI to allow users to easily see the source of the status.
      For example, if your continuous integration system is posting build status, you would want to provide the deep link for the build output for this specific SHA:
      http://ci.example.com/user/repo/build/sha

  wip_desc:
    required: false
    description: A short description of the status.
    default: work in progress

  ready_desc:
    required: false
    description: A short description of the status.
    default: ready for review

runs:
  using: node12
  main: dist/index.js

branding:
  icon: alert-triangle
  color: yellow
