name: 🚧　WIP
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  WIP:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/use-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          env_name: bot_token
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./
        with:
          # GITHUB_TOKEN: ${{ env.bot_token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config: |
            terms:
              - wip
              - work in progress
              - work-in-progress
              - do not merge
              - do-not-merge
              - rfc
              - 🚧
            locations:
              - title
              - label
              - commit
